import { writeFile } from "node:fs/promises";
import * as os from "node:os";
import * as path from "node:path";
import { APP_NAME } from "@oh-my-pi/pi-utils";
import { getUi, type SettingPath, settings } from "../config/settings";
import { SETTINGS_SCHEMA } from "../config/settings-schema";

export type EmitLayout = "grouped" | "flat";
export type PrefixOrder = "alpha" | "priority";

export interface EmitTomlOptions {
	layout: EmitLayout;
	prefixOrder: PrefixOrder;
	includeComments: boolean;
	includePriorityHeader: boolean;
	groupBulk: boolean;
	renameProviders: boolean;
	templateDate: string;
	outputTemplate: string;
	outputActive: string;
}

const IMPORTANCE: Record<string, Set<string>> = {
	ask: new Set(["notify", "timeout"]),
	astEdit: new Set(["enabled"]),
	astGrep: new Set(["enabled"]),
	async: new Set(["enabled", "maxJobs"]),
	bashInterceptor: new Set(["enabled"]),
	browser: new Set(["enabled", "headless", "screenshotDir"]),
	checkpoint: new Set(["enabled"]),
	commands: new Set(["enableClaudeProject", "enableClaudeUser"]),
	compaction: new Set([
		"enabled",
		"strategy",
		"thresholdPercent",
		"thresholdTokens",
		"remoteEnabled",
		"handoffSaveToDisk",
	]),
	completion: new Set(["notify"]),
	contextPromotion: new Set(["enabled"]),
	default: new Set([
		"modelRoles",
		"defaultThinkingLevel",
		"hideThinkingBlock",
		"disabledProviders",
		"disabledExtensions",
		"extensions",
	]),
	display: new Set(["showTokenUsage", "tabWidth"]),
	edit: new Set(["mode", "fuzzyMatch", "fuzzyThreshold", "blockAutoGenerated"]),
	exa: new Set(["enabled", "enableSearch", "enableResearcher", "enableWebsets"]),
	fetch: new Set(["enabled"]),
	find: new Set(["enabled"]),
	github: new Set(["enabled"]),
	grep: new Set(["enabled", "contextBefore", "contextAfter"]),
	images: new Set(["autoResize", "blockImages"]),
	inspect_image: new Set(["enabled"]),
	lsp: new Set(["enabled", "diagnosticsOnWrite", "formatOnWrite"]),
	providers: new Set(["image", "parallelFetch", "webSearch"]),
	mcp: new Set(["enableProjectConfig", "discoveryMode", "discoveryDefaultServers", "notifications"]),
	memories: new Set(["enabled"]),
	python: new Set(["toolMode", "kernelMode", "sharedGateway"]),
	read: new Set(["defaultLimit"]),
	retry: new Set(["enabled", "maxRetries", "baseDelayMs", "fallbackRevertPolicy"]),
	secrets: new Set(["enabled"]),
	skills: new Set(["enabled", "enableSkillCommands", "customDirectories", "ignoredSkills", "includeSkills"]),
	startup: new Set(["quiet", "checkUpdate"]),
	statusLine: new Set(["preset", "separator", "showHookStatus", "leftSegments", "rightSegments"]),
	task: new Set(["eager", "maxConcurrency", "maxRecursionDepth", "isolation.mode", "isolation.merge"]),
	terminal: new Set(["showImages"]),
	theme: new Set(["dark", "light"]),
	thinkingBudgets: new Set(["minimal", "low", "medium", "high", "xhigh"]),
	todo: new Set(["enabled", "reminders", "eager"]),
	tools: new Set(["intentTracing", "maxTimeout", "artifactSpillThreshold", "artifactTailBytes", "artifactTailLines"]),
	ttsr: new Set(["enabled", "contextMode", "interruptMode", "repeatMode"]),
	web_search: new Set(["enabled"]),
};

const PRIORITY_PREFIXES = [
	"default",
	"thinkingBudgets",
	"providers",
	"retry",
	"compaction",
	"contextPromotion",
	"task",
	"tools",
	"ttsr",
	"todo",
	"edit",
	"python",
	"lsp",
	"read",
	"grep",
	"find",
	"bashInterceptor",
	"mcp",
	"browser",
	"web_search",
	"exa",
	"fetch",
	"github",
	"skills",
	"secrets",
	"theme",
	"statusLine",
	"display",
] as const;

const PRIORITY_TIERS: Array<{ label: string; keys: string[] }> = [
	{
		label: "P0 runtime_cost_safety",
		keys: [
			"default.modelRoles",
			"default.defaultThinkingLevel",
			"retry.enabled",
			"retry.maxRetries",
			"compaction.enabled",
			"compaction.strategy",
			"compaction.thresholdPercent",
			"task.eager",
			"task.maxConcurrency",
			"tools.maxTimeout",
			"tools.intentTracing",
		],
	},
	{
		label: "P1 tooling_correctness",
		keys: [
			"bashInterceptor.enabled",
			"find.enabled",
			"grep.enabled",
			"astGrep.enabled",
			"astEdit.enabled",
			"lsp.enabled",
			"default.readHashLines",
			"python.toolMode",
		],
	},
	{
		label: "P2 integrations_external",
		keys: [
			"mcp.enableProjectConfig",
			"mcp.discoveryMode",
			"web_search.enabled",
			"browser.enabled",
			"github.enabled",
			"secrets.enabled",
			"fetch.enabled",
			"toolingProviders.webSearch",
		],
	},
	{
		label: "P3 ux_presentation",
		keys: [
			"theme.dark",
			"theme.light",
			"statusLine.preset",
			"statusLine.separator",
			"display.showTokenUsage",
			"default.hideThinkingBlock",
		],
	},
];

interface SettingMeta {
	path: string;
	description: string;
	value: unknown;
}

function splitKey(fullKey: string): { prefix: string; subkey: string } {
	const dotIndex = fullKey.indexOf(".");
	if (dotIndex === -1) return { prefix: "default", subkey: fullKey };
	return { prefix: fullKey.slice(0, dotIndex), subkey: fullKey.slice(dotIndex + 1) };
}

function displayPrefix(prefix: string, renameProviders: boolean): string {
	return renameProviders && prefix === "providers" ? "toolingProviders" : prefix;
}

function tomlEscape(value: string): string {
	return value.replaceAll("\\", "\\\\").replaceAll('"', '\\"');
}

function formatScalar(value: unknown): string {
	if (typeof value === "boolean") return value ? "true" : "false";
	if (typeof value === "number") return Number.isFinite(value) ? String(value) : '""';
	if (typeof value === "string") return `"${tomlEscape(value)}"`;
	if (Array.isArray(value)) return `[${value.map(item => formatScalar(item)).join(", ")}]`;
	if (value === null || value === undefined) return '""';
	throw new Error(`Unsupported scalar type: ${typeof value}`);
}

function orderedPrefixes(prefixes: string[], mode: PrefixOrder): string[] {
	if (mode === "alpha") return [...prefixes].sort();
	const priority = new Map<string, number>(PRIORITY_PREFIXES.map((name, index) => [name, index]));
	return [...prefixes].sort((a, b) => {
		const ai = priority.get(a) ?? PRIORITY_PREFIXES.length;
		const bi = priority.get(b) ?? PRIORITY_PREFIXES.length;
		return ai - bi || a.localeCompare(b);
	});
}

function pushHeader(lines: string[], options: EmitTomlOptions): void {
	if (!options.includeComments) return;
	lines.push(`# ${APP_NAME.toUpperCase()} settings reference template`);
	if (options.layout === "grouped") {
		lines.push(
			"# Grouping rule: repeated visual prefix headers; hot fields first, then more fields for the same prefix.",
		);
		lines.push("# Stable emission: prefixes sorted by configured order, fields alphabetized within each block.");
		lines.push(
			"# Roundtrip note: grouped mode is ergonomic, not canonical; keys emit as full dotted paths to stay TOML-valid.",
		);
	} else {
		lines.push("# Flat rule: full setting paths emitted in alphabetical order.");
		lines.push("# Roundtrip note: this mode avoids prefix regrouping and provider relabeling drift.");
	}
	lines.push("");
	if (!options.includePriorityHeader) return;
	lines.push("# Proposed importance ordering");
	for (const tier of PRIORITY_TIERS) {
		lines.push(`# [${tier.label}]`);
		for (const key of tier.keys) lines.push(`# - ${key}`);
	}
	lines.push("");
}

function emitPrefixedBlock(
	lines: string[],
	prefixLabel: string,
	items: SettingMeta[],
	includeComments: boolean,
	blockLabel: string,
): void {
	lines.push(`# [${prefixLabel}] ${blockLabel}`);
	if (items.length === 0) {
		if (includeComments) lines.push("# (none)");
		lines.push("");
		return;
	}
	for (const item of items) {
		if (includeComments && item.description) lines.push(`# ${item.description}`);
		const value = item.value;
		const fullPath = `${prefixLabel}.${item.path}`;
		if (value && typeof value === "object" && !Array.isArray(value)) {
			const record = value as Record<string, unknown>;
			const keys = Object.keys(record).sort();
			if (keys.length === 0) {
				lines.push(`"${fullPath}" = {}`);
			} else {
				lines.push(`["${fullPath}"]`);
				for (const key of keys) {
					const nestedValue = record[key];
					if (nestedValue && typeof nestedValue === "object" && !Array.isArray(nestedValue)) {
						const rendered = JSON.stringify(
							nestedValue,
							Object.keys(nestedValue as Record<string, unknown>).sort(),
						);
						lines.push(`"${key}" = "${tomlEscape(rendered)}"`);
					} else {
						lines.push(`"${key}" = ${formatScalar(nestedValue)}`);
					}
				}
			}
		} else if (Array.isArray(value) && value.length > 0 && typeof value[0] === "object" && value[0] !== null) {
			lines.push(`"${fullPath}" = []`);
			for (const entry of value as Array<Record<string, unknown>>) {
				lines.push(`[["${fullPath}"]]`);
				for (const key of Object.keys(entry).sort()) {
					lines.push(`${key} = ${formatScalar(entry[key])}`);
				}
			}
		} else {
			lines.push(`"${fullPath}" = ${formatScalar(value)}`);
		}
		lines.push("");
	}
}

function renderGrouped(options: EmitTomlOptions, settingsByPrefix: Map<string, SettingMeta[]>): string {
	const lines: string[] = [];
	pushHeader(lines, options);
	for (const rawPrefix of orderedPrefixes([...settingsByPrefix.keys()], options.prefixOrder)) {
		const shownPrefix = displayPrefix(rawPrefix, options.renameProviders);
		const items = [...(settingsByPrefix.get(rawPrefix) ?? [])].sort((a, b) => a.path.localeCompare(b.path));
		if (!options.groupBulk) {
			emitPrefixedBlock(lines, shownPrefix, items, options.includeComments, "all");
			lines.push("");
			continue;
		}
		const importance = IMPORTANCE[rawPrefix] ?? new Set<string>();
		const userItems = items.filter(item => importance.has(item.path) || importance.has(`${rawPrefix}.${item.path}`));
		const bulkItems = items.filter(item => !userItems.includes(item));
		emitPrefixedBlock(lines, shownPrefix, userItems, options.includeComments, "hot");
		emitPrefixedBlock(lines, shownPrefix, bulkItems, options.includeComments, "more");
		lines.push("");
	}
	return `${lines.join("\n").trimEnd()}\n`;
}

function renderFlat(options: EmitTomlOptions, allSettings: SettingMeta[]): string {
	const lines: string[] = [];
	pushHeader(lines, { ...options, renameProviders: false, groupBulk: false });
	for (const item of [...allSettings].sort((a, b) => a.path.localeCompare(b.path))) {
		if (options.includeComments && item.description) lines.push(`# ${item.description}`);
		const value = item.value;
		if (value && typeof value === "object" && !Array.isArray(value)) {
			const record = value as Record<string, unknown>;
			const keys = Object.keys(record).sort();
			if (keys.length === 0) {
				lines.push(`"${item.path}" = {}`);
			} else {
				lines.push(`["${item.path}"]`);
				for (const key of keys) {
					const nestedValue = record[key];
					if (nestedValue && typeof nestedValue === "object" && !Array.isArray(nestedValue)) {
						const rendered = JSON.stringify(
							nestedValue,
							Object.keys(nestedValue as Record<string, unknown>).sort(),
						);
						lines.push(`"${key}" = "${tomlEscape(rendered)}"`);
					} else {
						lines.push(`"${key}" = ${formatScalar(nestedValue)}`);
					}
				}
			}
		} else if (Array.isArray(value) && value.length > 0 && typeof value[0] === "object" && value[0] !== null) {
			lines.push(`"${item.path}" = []`);
			for (const entry of value as Array<Record<string, unknown>>) {
				lines.push(`[["${item.path}"]]`);
				for (const key of Object.keys(entry).sort()) lines.push(`${key} = ${formatScalar(entry[key])}`);
			}
		} else {
			lines.push(`"${item.path}" = ${formatScalar(value)}`);
		}
		lines.push("");
	}
	return `${lines.join("\n").trimEnd()}\n`;
}

function collectSettings(): { byPrefix: Map<string, SettingMeta[]>; flat: SettingMeta[] } {
	const byPrefix = new Map<string, SettingMeta[]>();
	const flat: SettingMeta[] = [];
	for (const key of Object.keys(SETTINGS_SCHEMA) as SettingPath[]) {
		const description = getUi(key)?.description ?? "";
		const value = settings.get(key);
		const entry: SettingMeta = { path: key, description, value };
		flat.push(entry);
		const { prefix, subkey } = splitKey(key);
		const arr = byPrefix.get(prefix) ?? [];
		arr.push({ path: subkey, description, value });
		byPrefix.set(prefix, arr);
	}
	return { byPrefix, flat };
}

export async function emitSettingsToml(options: EmitTomlOptions): Promise<string> {
	const { byPrefix, flat } = collectSettings();
	const content = options.layout === "flat" ? renderFlat(options, flat) : renderGrouped(options, byPrefix);
	await writeFile(options.outputTemplate, content, "utf8");
	await writeFile(options.outputActive, content, "utf8");
	return content;
}

export function defaultEmitOptions(templateDate: string): EmitTomlOptions {
	return {
		layout: "grouped",
		prefixOrder: "priority",
		includeComments: true,
		includePriorityHeader: true,
		groupBulk: true,
		renameProviders: true,
		templateDate,
		outputTemplate: path.join(os.homedir(), ".agent", `ohp-settings-template-${templateDate}.toml`),
		outputActive: path.join(os.homedir(), ".agent", "ohp-settings.toml"),
	};
}
